import dns from "node:dns";
dns.setDefaultResultOrder("ipv4first");
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Manrope } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const manrope = Manrope({
	variable: "--font-manrope-",
	subsets: ["latin"],
});

export const metadata = {
	title: "Hireloop | Home",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			data-theme="dark"
			className={`${manrope.className}  dark h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<Navbar></Navbar>
				<main>{children}</main>
				<Footer></Footer>
				<Toaster position="top-center" reverseOrder={false} />
			</body>
		</html>
	);
}
